version: '3.8'
services:
  web-server:
    image: nginx:1.19-alpine
    container_name: ${APP_NAME}-webserver
    working_dir: /application
    volumes: 
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/application
    networks: 
      - equipment-manager
    ports:
      - 8080:80
    restart: always
  php-fpm:
    build: ./docker/php
    image: ${APP_NAME}-php
    container_name: ${APP_NAME}-api
    working_dir: /application
    volumes:
      - .:/application
    networks:
      - equipment-manager
    restart: always
  database:
    image: mysql:5.7
    container_name: ${APP_NAME}-database
    environment: 
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    networks:
      - equipment-manager
    restart: always
    
    
networks:
  equipment-manager:
    driver: bridge
volumes: 
  data:
    name: mysql-data